### ISSUE TITLE
Failed navigation on Windows

### ISSUE THREAD

**Issue by acdupont** [vrerv/mkdocs-gen-nav-plugin#3]
Documentation generated on Windows results in navigation errors on files that are descendants of a subdirectories. The error is similar to:
```
This site can’t be reached
The webpage at file:///C:/gen-nav/site/TopSection%5Cwillerror.html
might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_URL
```

I believe the `%5C` comes from processing `\` characters on Windows paths. I tried using `/` [here](https://github.com/vrerv/mkdocs-gen-nav-plugin/blob/f00303fec3e5b52187bb101c23a1b5df22da6e65/src/mkdocs_gen_nav_plugin/plugin.py#L36) by using `Path().as_posix()` rather than `os.path.join`, and it resulted in a working website.

Here is a zip of minimal code I used to demonstrate the behavior on my machine:
[gen-nav.zip](https://github.com/user-attachments/files/17156412/gen-nav.zip)

![willerror](https://github.com/user-attachments/assets/33e0b0bf-dbf4-492a-8eb2-01c621d9d406)
![willerror-fix](https://github.com/user-attachments/assets/997b22e0-3215-4b17-9655-a95f7cfe9eca)

**Comment by sh1nj1** [comment]
Thank you for the report @acdupont 
I am looking at it, it is easy to change to use '/' but I found that it looks like I still see "%5C" even though I use "/" in nav configuration.
Besides, it will work if you open it with Http Server, like "mkdocs serve" or "python -m http.server -d ./site"
What `mkdocs` version you use?

**Comment by sh1nj1** [comment]
@acdupont try to use 0.1.2
it will use POSIX path separator to generate nav configuration on Windows OS

**Comment by acdupont** [comment]
I am using python 3.9.1, here are the dependencies from the virtual environment from the sample code:
```
(.venv) C:\gen-nav>python -m pip list
Package               Version
--------------------- -----------
click                 8.1.7
colorama              0.4.6
ghp-import            2.1.0
importlib-metadata    8.5.0
jinja2                3.1.4
Markdown              3.7
MarkupSafe            2.1.5
mergedeep             1.3.4
mkdocs                1.6.1
mkdocs-gen-nav-plugin 0.1.1
mkdocs-get-deps       0.2.0
packaging             24.1
pathspec              0.12.1
pip                   20.2.3
platformdirs          4.3.6
python-dateutil       2.9.0.post0
PyYAML                6.0.2
pyyaml-env-tag        0.1
setuptools            49.2.1
six                   1.16.0
watchdog              5.0.2
zipp                  3.20.2
```

**Comment by acdupont** [comment]
I get the same behavior with 0.1.2. The line in question is still using `os.path.join` [here](https://github.com/vrerv/mkdocs-gen-nav-plugin/blob/61c203baad73cd0ff5eaf7f0649e2436283ce810/src/mkdocs_gen_nav_plugin/plugin.py#L38). I confirmed converting the result to posix paths works in 0.1.2.

I also tried some sample code with `posixpath`, and you may want to use `pathlib.Path`:
```
>>> posixpath.join("C:\\my\\windows\\path", "another", "couple", "paths")
'C:\\my\\windows\\path/another/couple/paths'
>>> (Path("C:\\my\\windows\\path")/"another"/"couple"/"paths").as_posix()
'C:/my/windows/path/another/couple/paths'
```

**Comment by acdupont** [comment]
I should mention I'm not serving the generated documentation. I'm accessing it directly from the file system.

**Comment by sh1nj1** [comment]
@acdupont please try to use 0.2.0

**Comment by acdupont** [comment]
Yup, that fixes it for me! Thanks for the super quick responses and patch speed!
